module.exports = [
  {
    personID: 1,
    firstName: "Dewan",
    lastName: "Zaman",
    nationality: "Bangladesh",
    townOfOrigin: "Dhaka",
    addressOfOrigin: "111 Bashabo Road, Bashabo",
    photo: "",
    email: "dewan.zaman@gmail.com",
    interestID: 1,
    birthday: 213121241,
    description: "",
    address: "16 Carel Road, Wellington, Sussex, SW3 3TL",
  },
  {
    personID: 2,
    firstName: "Elena",
    lastName: "Rodrigues",
    nationality: "Portugal",
    townOfOrigin: "Lisbon",
    addressOfOrigin: "111 Goanese Alley, Goa",
    photo: "",
    email: "el.rod@gmail.com",
    interestID: 2,
    birthday: 213121241,
    description: "",
    address: "116 Parella Avenue, Cornwall, Devon, EX3 3AA",
  },
  {
    personID: 3,
    firstName: "Tobi",
    lastName: "George",
    nationality: "Nigeria",
    townOfOrigin: "Lagos",
    addressOfOrigin: "33 Lagoan Road, Lagos",
    photo: "",
    email: "o.george@gmail.com",
    interestID: 3,
    birthday: 213121241,
    description: "",
    address: "16 Castrel Road, Budson, Surrey, SW3 3TL",
  },
];
