module.exports = [
  {
    personID: 1,
    firstName: "Dewan",
    lastName: "Zaman",
    nationality: "Bangladesh",
    townOfOrigin: "Dhaka",
    addressOfOrigin: "111 Bashabo Road, Bashabo",
    photo: "",
    email: "dewan.zaman@gmail.com",
    interestID: 1,
    birthday: 213121241,
    description: "",
    address: "16 Carleton Avenue, Wallington, Surrey",
    postcode: "SM6 9LN",
    latitude: 51.349577,
    longitude: -0.138444,
  },
  {
    personID: 2,
    firstName: "Elena",
    lastName: "Rodrigues",
    nationality: "Portugal",
    townOfOrigin: "Lisbon",
    addressOfOrigin: "111 Goanese Alley, Goa",
    photo: "",
    email: "el.rod@gmail.com",
    interestID: 2,
    birthday: 213121241,
    description: "",
    address: "99 Portland Street, Exeter",
    postcode: "EX4 4NA",
    latitude: 50.736074,
    longitude: -3.54453,
  },
  {
    personID: 3,
    firstName: "Tobi",
    lastName: "George",
    nationality: "Nigeria",
    townOfOrigin: "Lagos",
    addressOfOrigin: "33 Lagoan Road, Lagos",
    photo: "",
    email: "o.george@gmail.com",
    interestID: 3,
    birthday: 213121241,
    description: "",
    address: "16 Castrel Road, Budson, Surrey",
    postcode: "SW3 3TL",
    latitude: 51.452261,
    longitude: -0.174239,
  },
];
